# rocksdb_binding.pyi

from typing import Optional, Dict, List

class RocksDB:
    def __init__(self) -> None: ...
    def open(self, db_path: str) -> bool: ...
    def put(self, key: str, value: str) -> bool: ...
    def get(self, key: str) -> Optional[str]: ...
    def multiget(self, keys: List[str]) -> Dict[str, Optional[str]]: ...
    def delete(self, key: str) -> bool: ...
    def set_custom_option(self, value: int) -> None: ...

class Options:
    def __init__(self) -> None: ...
    create_if_missing: bool
    max_open_files: int
